<?php

namespace ResponsabilitesBundle\Repository;

/**
 * ExtraJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraJobRepository extends \Doctrine\ORM\EntityRepository
{
}
