<?php

namespace ResponsabilitesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	public function getPaginedMenus($page, $nbPerPage)
	{
		$query = $this
			->createQueryBuilder('m')
			->orderBy('m.id', 'DESC')
			->getQuery();

		$query
			->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}
}
