<?php

namespace ResponsabilitesBundle\Repository;

/**
 * ObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetRepository extends \Doctrine\ORM\EntityRepository
{
	public function getWithTypeById($id)
	{
		$qb = $this->createQueryBuilder('o');

		$qb->leftJoin('o.type', 't')
			->addSelect('t')
			->where($qb->expr()->eq('o.id', ':id'))
			->setParameter('id', (int) $id);

		return $qb->getQuery()->getOneOrNullResult();
	}
}
