<?php

namespace ResponsabilitesBundle\Repository;

/**
 * TypeObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeObjetRepository extends \Doctrine\ORM\EntityRepository
{
	public function getWithObjetsById($id)
	{
		$qb = $this
			->createQueryBuilder('t')
			->leftJoin('t.objets', 'o')
			->addSelect('o')
			->where($qb->expr()->eq('t.id', ':id'))
			->setParameter('id', (int) $id);

		return $qb->getQuery()->getResult();
	}
}
