services:
    core.mailer:
        class: CoreBundle\Mailer\Mailer
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - {template: {chefs: "CoreBundle:Chefs:email.html.twig"}, mailer_user: "%mailer_user%"}
