services:
    core.mailer:
        class: CoreBundle\Mailer
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - parameters:
                template:
                    chefs: "CoreBundle:Chefs:email.html.twig"
                mailer_user: "%mailer_user%"
