services:
    core.mailer:
        class: CoreBundle\Mailer\Mailer
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - {template: {chefs: "CoreBundle:Chefs:email.html.twig"}, mailer_user: "%mailer_user%"}
    core.chatbot:
        class: CoreBundle\Chatbot\Chatbot
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - 
                repositoryName:
                    chat: CoreBundle:Chat
                    user: UserBundle:User
                chatbotUsername: chatbot
                role_admin: ROLE_CHEF
