services:
    core.mailer:
        class: CoreBundle\Mailer\Mailer
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - 
                template:
                    chefs:        "CoreBundle:Chefs:email.html.twig"
                    confirmation: "UserBundle:Registration:email.txt.twig"
                    resetting:    "UserBundle:Resetting:email.txt.twig"
                    contact:      "CoreBundle:Index:contact_email.html.twig"
                mailer_user: "%mailer_user%"
                from_email:
                    confirmation: "%mailer_user%"
                    resetting:    "%mailer_user%"
                to_email:
                    contact: "%mailer_user%"
    core.chatbot:
        class: CoreBundle\Chatbot\Chatbot
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@router"
            - "@translator"
            - 
                repositoryName:
                    chat: CoreBundle:Chat
                    user: UserBundle:User
                chatbotUsername: chatbot
                role_admin: ROLE_CHEF
                route:
                    view_actu: core_actus_viewone
    core.listener:
        class: CoreBundle\Event\EventListener
        arguments:
            - "@core.chatbot"
        tags:
            - { name: kernel.event_listener, event: caravane.new_actu,             method: newActu }
            - { name: kernel.event_listener, event: fos_user.registration.success, method: newUser }
    core.comments_parser:
        class: CoreBundle\CommentsParser
        arguments:
            - "@fm_bbcode.twig.extension"
            - comments_filter
    core.calendr_event_provider:
        class: CoreBundle\Repository\EventRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['CoreBundle:Event']
        tags:
            - { name: calendr.event_provider }
