user_ban_ban:
    path: /{user}/ban
    defaults:
        _controller: UserBundle:Ban:ban
    methods: GET

user_ban_deban:
    path: /{user}/deban
    defaults:
        _controller: UserBundle:Ban:deban
    methods: GET
