user_role_view:
    path: /voir
    defaults:
        _controller: UserBundle:Role:view
    methods: GET

user_role_edit:
    path: /voir/{username}
    defaults:
        _controller: UserBundle:Role:edit
    methods: GET|POST
