imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    nb_per_page: 10

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: UserBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: UserBundle\Form\Type\RegistrationFormType
    from_email:
        address: nilsdu29@gmail.com
        sender_name: "Nils Van Zuijlen"
    service:
        mailer: core.mailer
    group:
        group_class: UserBundle\Entity\Group
    profile:
        form:
            type: UserBundle\Form\Type\ProfileFormType
    change_password:
        form:
            type: UserBundle\Form\Type\ChangePasswordFormType
    resetting:
        form:
            type: UserBundle\Form\Type\ResettingFormType
    group:
        form:
            type: UserBundle\Form\Type\GroupFormType

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

#AsseticBundle
assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles: 
        - FOSCommentBundle
        - CoreBundle

#FMBbcodeBundle
fm_bbcode:
    filter_sets:
        all:
            strict: false
            locale: "%locale%"
            xhtml: false
            hooks: [ emoticon, clickable ]
            filters: [ default, block, code, email, image, list, quote, text, url, video, table ]
        actus_filter:
            strict:  false
            locale:  "%locale%"
            xhtml:   false
            filters: [ default, url, email, block, code, image, list, quote, text, video, table ]
            hooks:   [ emoticon, clickable ]
        chat_filter:
            strict:  false
            locale:  "%locale%"
            xhtml:   false
            hooks:   [ emoticon, clickable ]
            filters: [ default, url, email ]
        comments_filter:
            strict:  false
            locale:  "%locale%"
            xhtml:   false
            hooks:   [ emoticon, clickable ]
            filters: [ default, url, email, block, code, image, list, quote, text ]
        events_filter:
            strict:  false
            locale:  "%locale%"
            xhtml:   false
            hooks:   [ emoticon, clickable ]
            filters: [ default, url, email, block, code, image, list, quote, text, table, video ]
        responsabilites_filter:
            strict: false
            locale: "%locale%"
            xhtml: false
            hooks: [ emoticon, clickable ]
            filters: [ default, url, email, code, list, quote ]
    emoticon:
        path:      /emoticons/
        resource:  "%kernel.root_dir%/config/emoticons.yml"
        extension: gif

# FOSCommentBundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: CoreBundle\Entity\Comment
            thread:  CoreBundle\Entity\Thread
    acl: true
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_REMEMBERED
            view: IS_AUTHENTICATED_REMEMBERED
            edit: ROLE_MODERATOR
            delete: ROLE_MODERATOR
        thread:
            create: IS_AUTHENTICATED_REMEMBERED
            view: IS_AUTHENTICATED_REMEMBERED
            edit: ROLE_MODERATOR
            delete: ROLE_MODERATOR
        vote:
            create: IS_AUTHENTICATED_REMEMBERED
            view: IS_AUTHENTICATED_REMEMBERED
            edit: ROLE_MODERATOR
            delete: ROLE_MODERATOR
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl

# KNPPaginatorBundle
knp_paginator:
    page_range: 3
    default_options:
        page_name: caravane
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# DForumBundle
discutea_forum:
    preview:
        enabled: true
    knp_paginator:
        page_name: caravane  #voir knp_paginator.default_option.page_name
        topics:
            enabled: true
            per_page: "%nb_per_page%"
        posts:
            enabled: true
            per_page: "%nb_per_page%"
