core:
    resource: "@CoreBundle/Resources/config/routing/all.yml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

user:
    resource: "@UserBundle/Resources/config/routing/all.yml"

responsabilites:
    resource: "@ResponsabilitesBundle/Resources/config/routing/all.yml"
    prefix:   /responsabilites
