core:
    resource: "@CoreBundle/Resources/config/routing/all.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

fos_user_group:
    resource: "@UserBundle/Resources/config/routing/group.xml"
    prefix: /equipes

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

user_role:
    resource: "@UserBundle/Resources/config/routing/role.yml"
    prefix:   /responsabilites

responsabilites:
    resource: "@ResponsabilitesBundle/Resources/config/routing/all.yml"
    prefix:   /responsabilites

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /

remove_trailing_slash: # MUST BE LAST ROUTE
    path: /{url}
    defaults: { _controller: CoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
