core_index:
    resource: "@CoreBundle/Resources/config/routing/index.yml"

core_chefs:
    resource: "@CoreBundle/Resources/config/routing/chefs.yml"
    prefix:   /chefs

core_chat:
    resource: "@CoreBundle/Resources/config/routing/chat.yml"
    prefix:   /chat