core_index:
    resource: "@CoreBundle/Resources/config/routing/index.yml"

core_chefs:
    resource: "@CoreBundle/Resources/config/routing/chefs.yml"
    prefix:   /chefs

core_chat:
    resource: "@CoreBundle/Resources/config/routing/chat.yml"
    prefix:   /chat

core_actus:
    resource: "@CoreBundle/Resources/config/routing/actus.yml"
    prefix:   /actus

core_file:
    resource: "@CoreBundle/Resources/config/routing/file.yml"
    prefix:   /fichier

core_event:
    resource: "@CoreBundle/Resources/config/routing/event.yml"
    prefix:   /evenements
