core_event_view_by_day:
    path: /calendrier/{year}/{month}/{day}
    defaults:
        _controller: CoreBundle:Event:viewByDay
    requirements:
        year:  \d{4}
        month: \d{1,2}
        day:   \d{1,2}
    methods: GET

core_event_view_by_month:
    path: /calendrier/{year}/{month}
    defaults:
        _controller: CoreBundle:Event:viewByMonth
    requirements:
        year:  \d{4}
        month: \d{1,2}
    methods: GET

core_event_view_by_year:
    path: /calendrier/{year}
    defaults:
        _controller: CoreBundle:Event:viewByYear
    requirements:
        year: \d{4}
    methods: GET

core_event_add:
    path: /add
    defaults:
        _controller: CoreBundle:Event:add
    methods: GET|POST

core_event_viewone:
    path: /{uid}
    defaults:
        _controller: CoreBundle:Event:viewOne
    requirements:
        uid: ^[a-z0-9-]+$
    methods: GET

core_event_edit:
    path: /{uid}/edit
    defaults:
        _controller: CoreBundle:Event:edit
    requirements:
        uid: ^[a-z0-9-]+$
    methods: GET|POST

core_event_delete:
    path: /{uid}/delete
    defaults:
        _controller: CoreBundle:Event:delete
    requirements:
        uid: ^[a-z0-9-]+$
    methods: GET
