
index:
    path:     /
    defaults: { _controller: ResponsabilitesBundle:Intendance:index }

view_menu:
    path:     /viewMenu
    defaults: { _controller: ResponsabilitesBundle:Intendance:viewMenu }

new_menu:
    path:     /menu/nouveau
    defaults: { _controller: ResponsabilitesBundle:Intendance:newMenu }

edit_menu:
    path:     /menu/{slug}/edit
    defaults: { _controller: ResponsabilitesBundle:Intendance:editMenu }

view_all_menu:
    path:     /menu
    defaults: { _controller: ResponsabilitesBundle:Intendance:viewAllMenu }
