responsabilites_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    ResponsabilitesBundle::index.html.twig

responsabilites_animation:
    prefix:   /animation
    resource: animation.yml
