responsabilites_materiel_index:
    path: /
    defaults:
        _controller: ResponsabilitesBundle:Materiel:index
    methods: GET

responsabilites_materiel_new_type:
    path: /inventaire/types/nouveau
    defaults:
        _controller: ResponsabilitesBundle:Materiel:newType
    methods: GET|POST

responsabilites_materiel_view_type:
    path: /inventaire/types/{type}
    defaults:
        _controller: ResponsabilitesBundle:Materiel:viewType
    requirements:
        type: \d*
    methods: GET

responsabilites_materiel_new_objet:
    path: /inventaire/objets/nouveau
    defaults:
        _controller: ResponsabilitesBundle:Materiel:newObjet
    methods: GET|POST

responsabilites_materiel_view_objet:
    path: /inventaire/objets/{objet}
    defaults:
        _controller: ResponsabilitesBundle:Materiel:viewObjet
    requirements:
        type:  \d*
        objet: \d*
    methods: GET

responsabilites_materiel_view_all_objet:
    path: /inventaire/objets
    defaults:
        _controller: ResponsabilitesBundle:Materiel:viewAllObjet
    methods: GET

responsabilites_materiel_view_all_type:
    path: /inventaire/types
    defaults:
        _controller: ResponsabilitesBundle:Materiel:viewAllType
    methods: GET
