forum_forum_add_forum:
    path: /new/forum
    defaults:
        _controller: ForumBundle:Forum:addForum
    methods: GET|POST

forum_forum_edit_forum:
    path: /{categorie}/{slug}/edit
    defaults:
        _controller: ForumBundle:Forum:editForum
    requirements:
        categorie: ^[a-z0-9-]+$
        slug:      ^[a-z0-9-]+$
    methods: GET|POST

forum_forum_view:
    path: /{categorie}/{slug}
    defaults:
        _controller: ForumBundle:Forum:view
    requirements:
        categorie: ^[a-z0-9-]+$
        slug:      ^[a-z0-9-]+$
    methods: GET

forum_forum_view_categories:
    path: /
    defaults:
        _controller: ForumBundle:Forum:viewCategories
    methods: GET

forum_forum_view_categorie:
    path: /{categorie}
    defaults:
        _controller: ForumBundle:Forum:viewCategorie
    requirements:
        categorie: ^[a-z0-9-]+$
    methods: GET
