<?php

namespace CoreBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLast($number=1)
	{
		$qb = $this->createQueryBuilder('c');

		$qb
			->orderBy('c.id', 'DESC')
			->setMaxResults($number);

		$return = $qb->getQuery()->getResult();
		krsort($return, SORT_NUMERIC);
		return $return;
	}

	public function eraseAll()
	{
		$query = $this->_em->createQuery('DELETE CoreBundle:Chat c');
		$query->execute();
	}
}
