<?php

namespace CoreBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLast($number=1)
	{
		$qb = $this->createQueryBuilder('c');

		$qb
			->orderBy('c.sentTime', 'DESC')
			->setMaxResults($number);

		$return = $qb->getQuery()->getArrayResult();
		krsort($return, SORT_NUMERIC);
		return $return;
	}
}
